# Generated by Django 4.1.2 on 2024-06-01 17:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.CharField(choices=[('active', 'active'), ('inactive', 'inaive')], max_length=70)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcreated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.CharField(choices=[('active', 'active'), ('inactive', 'inaive')], max_length=70)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screated_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('code', models.IntegerField(unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('ntid', models.CharField(max_length=14)),
                ('brithday', models.DateField(default=datetime.datetime.now)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.CharField(choices=[('active', 'active'), ('inactive', 'inaive')], max_length=70)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.section')),
            ],
        ),
    ]
