# Generated by Django 4.1.2 on 2024-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='stat',
            field=models.CharField(choices=[('inactive', 'inaive'), ('active', 'active')], max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stat',
            field=models.CharField(choices=[('inactive', 'inaive'), ('active', 'active')], max_length=70),
        ),
        migrations.AlterField(
            model_name='section',
            name='stat',
            field=models.CharField(choices=[('inactive', 'inaive'), ('active', 'active')], max_length=70),
        ),
    ]
