# Generated by Django 4.1.2 on 2024-06-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_department_stat_alter_employee_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
    ]
