# Generated by Django 4.1.2 on 2024-06-07 16:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_remove_department_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ntid',
        ),
        migrations.AddField(
            model_name='department',
            name='no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999999999)]),
        ),
        migrations.AddField(
            model_name='section',
            name='no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_section', to='employee.section'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_department', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_specialty', to='employee.college')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college_education', to='employee.education'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('stat', models.BooleanField(default=True)),
                ('gov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='City_Gov', to='employee.gov')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_bank', to='employee.bank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_city', to='employee.city'),
        ),
        migrations.AddField(
            model_name='employee',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_college', to='employee.college'),
        ),
        migrations.AddField(
            model_name='employee',
            name='costcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_cost', to='employee.costcenter'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_education', to='employee.education'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_gender', to='employee.gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_gov', to='employee.gov'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_jobtitle', to='employee.jobtitle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='maritalstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_marital', to='employee.maritalstatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='militarystatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_military', to='employee.militarystatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_policy', to='employee.team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_region', to='employee.region'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_specialty', to='employee.specialty'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_team', to='employee.team'),
        ),
    ]
