# Generated by Django 5.0.6 on 2024-06-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_bankaccount_alter_bank_no_alter_city_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='brithday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hiredate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
