# Generated by Django 5.0.6 on 2024-06-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_payroll_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='college',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='costcenter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='maritalstatus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='militarystatus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='section',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
    ]
