# Generated by Django 4.1.2 on 2024-06-07 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expensive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('home', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payrolli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=45, unique=True)),
                ('dbname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Payrollmonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('abasic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aadditinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aincentives', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aexpensive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achanges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atrans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afood', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=45, unique=True)),
                ('overtime', models.FloatField(default=1.7, max_length=4)),
                ('overdays', models.FloatField(default=2, max_length=4)),
                ('monthdays', models.FloatField(default=30, max_length=2)),
                ('dailyhours', models.FloatField(default=8, max_length=2)),
                ('late', models.BooleanField(default=False)),
                ('early', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payrollt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('basic', models.FloatField(default=0)),
                ('vbasic', models.FloatField(default=0)),
                ('nbasic', models.FloatField(default=0)),
                ('additinal', models.FloatField(default=0)),
                ('vadditinal', models.FloatField(default=0)),
                ('nadditinal', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('vbonus', models.FloatField(default=0)),
                ('nbonus', models.FloatField(default=0)),
                ('incentives', models.FloatField(default=0)),
                ('vincentives', models.FloatField(default=0)),
                ('nincentives', models.FloatField(default=0)),
                ('expensive', models.FloatField(default=0)),
                ('vexpensive', models.FloatField(default=0)),
                ('nexpensive', models.FloatField(default=0)),
                ('changes', models.FloatField(default=0)),
                ('vchanges', models.FloatField(default=0)),
                ('nchanges', models.FloatField(default=0)),
                ('home', models.FloatField(default=0)),
                ('vhome', models.FloatField(default=0)),
                ('nhome', models.FloatField(default=0)),
                ('trans', models.FloatField(default=0)),
                ('vtrans', models.FloatField(default=0)),
                ('ntrans', models.FloatField(default=0)),
                ('nature', models.FloatField(default=0)),
                ('vnature', models.FloatField(default=0)),
                ('nnature', models.FloatField(default=0)),
                ('food', models.FloatField(default=0)),
                ('vfood', models.FloatField(default=0)),
                ('nfood', models.FloatField(default=0)),
                ('datef', models.DateField(default=0)),
                ('datet', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=45, unique=True)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expensive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('home', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
